---
title: ""
format: 
  pdf:
    documentclass: article
    geometry:
      - top=15mm
      - left=25mm
      - right=25mm
      - bottom=25mm
      - heightrounded
    fontfamily: libertinus
    colorlinks: true
    fontsize: 10pt
    include-in-header: 
      text: |
        \usepackage{setspace}
        \setstretch{1}
        \usepackage{fancyhdr}
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \pagestyle{fancy}
        \fancyhf{} % clear all header/footer fields
        \rfoot{\thepage} % right footer with page number
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}
        \setlength{\columnsep}{3cm}
        \usepackage{titlesec}
        \titlespacing*{\section}{0pt}{0.5em}{0.3em}
        \titlespacing*{\subsection}{0pt}{0.3em}{0.2em}
    keep-tex: true
---

\begin{flushright}
{\large \textbf{Prajyna P. Barua}}\\[0.5em]
\href{mailto:barua.prajyna@gmail.com}{Email} \quad | \quad
\href{https://www.linkedin.com/in/prajynabarua}{LinkedIn}\\[0.5em]
+1 201-850-9213
\end{flushright}

::: justify
November 01, 2025

Dear Members of the Search Committee,

I am writing to you to express my interest in the position of Assistant Professor for Economics at the AddRan College of Liberal Arts in Texas Christian University (TCU). I am Ph.D. candidate in Economics at the University of Texas at Dallas (UTD), expecting to graduate in December 2025. My primary research area is empirical macroeconomics and time series analysis, with secondary focus on Bayesian econometrics and econometrics. My dissertation focuses on understanding the driving forces behind cyclical behavior of unemployment and labor market efficiency in the U.S. economy and how incorporation of unemployment rate improves the output gap estimates. My research combines rich micro-level CPS data with modern state-space methodologies to answer these questions.

In my previous research experience as Research Fellow at Centre for WTO studies, India, I worked on evaluating the degree of market access provided across members countries under Trans-Pacific Partnership Agreement (TPP). This required analyzing large data sets from individual tariff schedules of several countries and sectors. I believe this background, combined with my current research on U.S. labor markets, positions me well to contribute to a department that values rigorous empirical research spanning both labor and international economics.
:::

,
