---
title: ""
format: 
  pdf:
    documentclass: article
    geometry:
      - top=15mm
      - left=25mm
      - right=25mm
      - bottom=25mm
      - heightrounded
    fontfamily: libertinus
    colorlinks: true
    fontsize: 10pt
    include-in-header: 
      text: |
        \usepackage{setspace}
        \setstretch{1}
        \usepackage{fancyhdr}
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \pagestyle{fancy}
        \fancyhf{} % clear all header/footer fields
        \rfoot{\thepage} % right footer with page number
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}
        \setlength{\columnsep}{3cm}
        \usepackage{titlesec}
        \titlespacing*{\section}{0pt}{0.5em}{0.3em}
        \titlespacing*{\subsection}{0pt}{0.3em}{0.2em}
    keep-tex: true
---

\begin{flushright}
{\large \textbf{Prajyna P. Barua}}\\[0.5em]
\href{mailto:barua.prajyna@gmail.com}{Email} \quad | \quad
\href{https://www.linkedin.com/in/prajynabarua}{LinkedIn}\\[0.5em]
+1 201-850-9213
\end{flushright}

::: justify
My research lies at the intersection of macroeconomics and labor economics, with specific focus on understanding the dynamics of the U.S. labor market. In particular, my research focuses on examining the factors affecting the shifts in the U.S. Beveridge Curve both at aggregate and industry level and contribute to the growing literature of labor market frictions and labor market flows. My primary research area is empirical macroeconomics and time series analysis, with secondary focus on Bayesian econometrics and econometrics. In general, my research approach is guided by asking seemingly simple questions—because even the simplest questions often demand deep analytical thinking and sophisticated empirical methods.

My dissertation consists of three chapters. My first chapter is my job market paper, titled '*Estimating time-variation in matching efficiency and match elasticity for the US labor market*' where I understand how labor market frictions evolved over time for the U.S. non-farm sector. In the paper, I estimate the time varying matching efficiency using state space model. I find evidence for significant time variation in matching efficiency which experienced a gradual decline, indicating growing labor market inefficiencies. I find matching efficiency to be pro-cyclical which can be attributed to increased reallocation of workers between industries and higher composition of non-degree wokers in the unemployed pool during the Great Recession. I find evidence of increased reallocation due to structural changes in the economy. I contribute to the literature by finding evidence of explaining matching efficiency using CPS data. For COVID-19, these factors were not significant. I also estimate unemployment gap using models with and without time variation and find counter intuitive gaps when time variation is not accounted for. Therefore my paper provides new insights on the shifting of the Beveridge Curve and highlights the importance of incorporating the micro-level data into macro-labor models.

Second chapter is titled '*Estimated ouput gap in a wage-inflation expectations model*' is a joint work with Azharul Islam, Irina Panovska and Srikanth Ramamurthy. Here we estimate output gap under bivariate adaptive learning process which allows feedback between wage and price inflation under New Keynesian Phillips Curve framework. Our output gap measures tracks the recessions

We study how incorporating adaptive learning-based inflation expectations for price and wage inflation can improve the performance of Unobserved Components (UC) models for estimating the output gap. We incorporate learning based expectations and bivariate feedback in the learning dynamics for wage and price inflation, and we augment a conventional reduced-form UC model for output and unemployment with this bivariate learning process. Our model directly integrates the expectations dynamics of the Hybrid New Keynesian Philips Curve while also retaining the appealing statistical features of the UC framework, allowing us to extract information about the output gap and about the expectation feedback between price and wage inflation. Three interesting sets of results stand out. First, our model captures turning points and the business cycle amplitude accurately, especially when when compared to models with univariate learning that do not incorporate labor market data. Second, while the perceived persistence of inflation fell during the early stages of the pandemic, it increased sharply and substantially 2021-2023. While it declined after 2024, it still remains at an elevated levem when compared to the pre-COVID period. Finally, we find that the cross-effects of wage and price inflation vary substantially over time.

In the future, I plan to deepen my research on the dynamics of unemployment. Specifically, I aim to examine how time variation in labor market matching efficiency influences inflation dynamics within a New Keynesian DSGE framework. Building on this line of inquiry, I also intend to extend my work on forecasting unemployment rates—both at the aggregate and industry levels—by utilizing transition probabilities, as recent studies suggest that incorporating flow-based measures enhances the accuracy of unemployment forecasts. Furthermore, I plan to expand my joint work on Mexico’s Beveridge Curve by constructing counterfactual unemployment paths to quantify the extent and sources of observed shifts. Lastly, I am also interested in exploring the potential economic benefits for African countries that are members of the West African Economic and Monetary Union, particularly in terms of economic growth and stability.
:::
