---
title: ""
format: 
  pdf:
    documentclass: article
    geometry:
      - top=15mm
      - left=15mm
      - right=15mm
      - bottom=15mm
      - heightrounded
    fontfamily: libertinus
    colorlinks: true
    fontsize: 8pt
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{comment}
        \usepackage{hyperref}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}
        \setlength{\columnsep}{3cm}
        \usepackage{titlesec}
        \titlespacing*{\section}{0pt}{0.5em}{0.3em}
        \titlespacing*{\subsection}{0pt}{0.3em}{0.2em}
    keep-tex: true
---

\begin{center}
{\huge \bf PRAJYNA BARUA} \\
barua.prajyna@gmail.com • Visa status: H4 EAD \footnote{Authorized to work in the United States} • \href{https://github.com/yourusername}{GitHub} • \href{https://www.linkedin.com/in/prajynabarua}{LinkedIn}
\end{center}

------------------------------------------------------------------------

\vspace{5pt} 
\begin{longtable*}{p{2cm}p{7cm}p{4cm}p{3cm}p{0cm}}
\textbf{Education} & University of Texas Dallas, Richardson, TX &  Ph.D. in Economics & \hfill 2020- December 2025\\
& Jawaharlal Nehru University, Delhi, India & M.Phil in Economics &  \hfill 2013 \\
& Delhi University, Delhi, India & B.A. Economics (Hons) & \hfill 2006\\ [10pt] 
\textbf{Research Interests} & Empirical Macroeconomics & Labor Economics & \hfill Business Cycle\\ [10pt] 
\textbf{Dissertation Title} & \multicolumn{4}{p{14cm}}{\emph{An Understanding of the US Labor Market from a Macroeconomic Perspective}} \\
\end{longtable*}
\begin{comment}
\begin{longtable*}{p{1.8cm}p{4.5cm}p{3cm}p{3cm}p{3cm}}
{\raggedright \textbf{Committee} \arraybackslash} & {\raggedright Irina B. Panovska (Chair)\arraybackslash}  & Patrick T. Brandt & Camilo Granados & \hfill Victor J. Valcarcel  \\
\end{longtable*}
\end{comment}
\begin{longtable*}{p{1.8cm}p{14.8cm}}
\textbf{Publication} & \href{https://sk.sagepub.com/book/mono/trans-pacific-partnership-agreement/chpt/2-tpp-market-access-goods} {\raggedright Das, A., Barua, P. and Philip, D. (2018). “TPP and market access for goods.” In Das, A. and Singh, S. (Ed.), Trans-pacific partnership agreement: a framework for future trade rules? (pp. 38-75). Sage Publications.
 \arraybackslash}\\
\end{longtable*}
\begin{longtable*}{p{1.7cm}p{14.8cm}}
\textbf{Working} & \href{https://} {\raggedright \textbf{Estimating time-variation in matching efficiency and match elasticity for the US labor market} \arraybackslash} (JMP)\\
\textbf{Papers}& \underline{Abstract}: The paper estimates time-varying matching efficiency and match elasticity within a Cobb-Douglas matching function for the U.S. non-farm sector, using a state-space model. It evaluates two specifications: (i) no constant returns to scale (CRS) with time variation (my baseline model) and (ii) CRS with time variation. I compare these two models with the standard model without time variability, and results show significant time variation in both parameters, even under stochastic volatility. Counterfactual vacancy estimates reveal that the non-CRS baseline model fits the data best. This model suggests a gradual decline in matching efficiency, indicating growing labor market inefficiencies. Matching efficiency and match elasticity with respect to unemployment are found to be procyclical. The procyclicality in efficiency can be attributed to reduced sectoral reallocation, as seen in IPUMS-CPS data, driven by structural economic shifts. Procyclical match elasticity points to the nonlinear effect of labor market tightness on the job-finding rate. The paper also finds a rise in the efficient unemployment rate after COVID-19, as estimated by the baseline model.\\[0.1pt]

& \href{https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5387586}{\raggedright \textbf{Mexico’s Formal Labor Market through the Lens of the Beveridge Curve} (with Luis F. Colunga-Ramos, Irina Panovska, Miroslava Quiroga-Trevino, B. Elam Rodriguez-Alcaraz) \arraybackslash}\\[0.1pt]

& {\raggedright \textbf{Estimated Output Gap in a Wage-Inflation Expectations Model} (with Azharul Islam, Irina Panovska and Srikanth Ramamurthy) \arraybackslash} \\[0.1pt]

& {\raggedright \textbf{Understanding unemployment dynamics} \arraybackslash}
\end{longtable*}
\begin{longtable*}{p{1.7cm}p{11.9cm}p{2.5cm}}
\textbf{Seminar and } & Western Economic Association International, 99th Annual Conference, Presenter, Seattle, Washington & \hfill July 2024\\
\textbf{Confer- }& Midwest Econometric Group Conference 2024, Presenter, Lexington, Kentucky &  \hfill November 2024 \\
\textbf{ences }& North Texas Economics Conference (NTxEC) 2024, Presenter, University of North Texas, Denton, Texas & \hfill November 2024\\
& Southern Economic Association, 94th Annual Meeting, Presenter, Washington D.C. & \hfill November 2024\\
&The Society for Nonlinear Dynamics and Econometrics, 32nd Annual Symposium, Presenter, University of Texas at San Antonio & \hfill March 2025 \\
&Southern Economic Association, 95th Annual Meeting, Graduate students session, Presenter, Tampa, Florida & \hfill November
2025 \\
& North Texas Economics Conference (NTxEC) 2025, Presenter, University of Texas at Arlington & \hfill November 2025\\
\end{longtable*}
\begin{longtable*}{p{1.6cm}p{12cm}p{2.5cm}}
\textbf{Awards} & Charles C. Mckinney Scholarship, University of Texas Dallas & \hfill 2025, 2024\\ 
\textbf{ and }& Irving J. Hoch Scholarship award, University of Texas Dallas. &  \hfill 2022 \\ 
\textbf{Fellow- }& Ph.D. Fellowship, University of Texas Dallas & \hfill 2020-2024\\ 
\textbf{ships }& Junior Research Fellowship, University Grant Commission, India & \hfill 2012-2014\\
\end{longtable*}
\begin{longtable*}{p{1.6cm}p{12cm}p{2.5cm}}
\textbf{Teaching Experi-} & \textit{Instructor}, ECON 2301 Principles of Macroeconomics, University of Texas Dallas. & {\raggedleft Su. 2023, 2024, Sp. 2025, Fall 2025\arraybackslash} \\
\textbf{ence}& \textit{Instructor}, \href{https://epps.utdallas.edu/mathcodingcamp/}{EPPS Math and Coding Boot Camp}, University of Texas Dallas: I served as one of the primary instructors for the Math Boot Camp designed for Master’s and incoming Ph.D. students. My responsibilities included developing course materials, delivering lectures, engaging with students through discussions and problem-solving sessions, and providing individualized feedback to support their academic preparation. &  
\hfill 2024, 2025 \\
& \textit{Teaching Assistant}, ECON 4386 Contemporary Macroeconomic Policy, University of Texas at Dallas & \hfill Fall 2023\\
& \textit{Teaching Assistant}, ECON 6303 Macroeconomics Theory I, University of Texas at Dallas & \hfill Fall 2023\\
& \textit{Teaching Assistant}, ECON 4385 Business and Econ Forecasting, University of Texas at Dallas & \hfill Spring 2023\\
& \textit{Teaching Assistant}, ECON 5397 Special Topics in Economics, University of Texas at Dallas & \hfill Spring 2023\\
& \textit{Teaching Assistant},  ECON 6306 Applied Econometrics, University of Texas at Dallas & \hfill Fall 2022\\
& \textit{Teaching Assistant}, ECON 4320 Public Sector Economics, University of Texas at Dallas & \hfill Spring 2022\\
& \textit{Teaching Assistant}, ECON 4302 Urban and Regional Economics, University of Texas at Dallas & \hfill Fall 2021\\
\end{longtable*}
\begin{longtable*}{p{1.6cm}p{12cm}p{2.5cm}}
\textbf{Research } & \underline{\textit{Research Assistant}}, University of Texas Dallas, Dr. Irina B. Panovska & \hfill Summer 2022\\
\textbf{Experi-} & \underline{\textit{Research Assistant}}, University of Texas Dallas, Dr. Denise P. Boots &  \hfill Summer 2021 \\
\textbf{ence}& \underline{\textit{Research Fellow}}, Centre for WTO Studies, New Delhi, India: 
I extensively worked on market access provided by Trans-Pacific Partnership Agreement to its members and the extent of India's comparative disadvantage by being part of it. This required analyzing detailed tariff schedules both at country and for specific sectors and, evaluating a comprehensive unit value analysis for all members. & \hfill 2015 – 2016 \\
& \underline {\textit{Programme Executive}}, United Nations Development Programme, India:
I was involved in preparation of the Bid document for hosting New Delhi as the NDB's (New Development Bank) Headquarters and provided brief reports on areas such as lending, governance, infrastructure financing, capital structure, and costing among others, with respect to the functioning of the NDB which were used as inputs for negotiations for the Articles of Agreement.  I also provided regular updates on the macroeconomic situation in BRICS economies, analyzing their economic trends, and policies. & \hfill 2013 – 2015\\
\end{longtable*}
\begin{longtable*}{p{1.8cm}p{14.8cm}}
\textbf{Software} & R, Matlab, Stata and Python \\
\end{longtable*}
\begin{longtable*}{p{1.8cm}p{14.85cm}}
\textbf{Academic} & Barua, P. (Chair), Macroeconomics 3, SNDE’25, San Antonio, Texas \\
\textbf{Service}& Discussant, WEAI’24 Session: “Trade Policies and the Relative Size of the Informal Sector in Developing Economies” by Mohammed Mohsin.\\
\end{longtable*}
\begin{longtable*}{p{1.8cm}p{4.6cm}p{4.8cm}p{4.8cm}}
{\raggedright \textbf{References}\arraybackslash} &
\textbf{Dr. Irina B. Panovska} & \textbf{Dr. Camilo Granados} &  \textbf{Dr. Victor Valcarcel}\\
&
Dissertation Chair &  &  \\
& Associate Professor of Economics &  Assistant Professor of Economics &  Professor of Economics\\
& The School of Economic, Political and Policy Sciences & The School of Economic, Political and Policy Sciences & The School of Economic, Political and Policy Sciences  \\
& University of Texas at Dallas &  University of Texas at Dallas & University of Texas at Dallas \\
& Richardson, TX 75080 & Richardson, TX 75080 & Richardson, TX 75080\\
& 972‑883‑6247 & &  972‑883‑6213\\
& \href{mailto:Irina.Panovska@utdallas.edu}{Irina.Panovska@utdallas.edu} &
\href{mailto:camilo.granados@utdallas.edu}{camilo.granados@utdallas.edu} &
\href{mailto:victor.valcarcel@utdallas.edu}{victor.valcarcel@utdallas.edu} \\
[1em]
\end{longtable*}
