---
title: "Teaching Experience"
format: 
  pdf:
    documentclass: article
    geometry:
      - top=15mm
      - left=15mm
      - right=15mm
      - bottom=15mm
      - heightrounded
    fontfamily: libertinus
    colorlinks: true
    fontsize: 8pt
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}
        \setlength{\columnsep}{3cm}
        \usepackage{titlesec}
        \titlespacing*{\section}{0pt}{0.5em}{0.3em}
        \titlespacing*{\subsection}{0pt}{0.3em}{0.2em}
    keep-tex: true
---

\renewcommand{\arraystretch}{1.3}
\begin{longtable*}{p{1.6cm}p{12cm}p{2.5cm}}
\textit{Instructor}& ECON 2301 Principles of Macroeconomics, University of Texas Dallas. & 

{\raggedright Su. 2023, 2024, Sp.2025, Fall2025\arraybackslash} \\

\textit{Instructor} & \href{https://epps.utdallas.edu/mathcodingcamp/}{EPPS Math and Coding Boot Camp}, University of Texas Dallas: I served as one of the primary instructors for the Math Boot Camp designed for Master’s and incoming Ph.D. students. My responsibilities included developing course materials, delivering lectures, engaging with students through discussions and problem-solving sessions, and providing individualized feedback to support their academic preparation. & \hfill 2024, 2025 \\

\textit{Teaching Assistant} & ECON 4386 Contemporary Macroeconomic Policy, University of Texas at Dallas & \hfill Fall 2023\\

\textit{Teaching Assistant} & ECON 6303 Macroeconomics Theory I, University of Texas at Dallas & \hfill Fall 2023\\

\textit{Teaching Assistant} & ECON 4385 Business and Econ Forecasting, University of Texas at Dallas & \hfill Spring 2023\\

\textit{Teaching Assistant} & ECON 5397 Special Topics in Economics, University of Texas at Dallas & \hfill Spring 2023\\

\textit{Teaching Assistant} &  ECON 6306 Applied Econometrics, University of Texas at Dallas & \hfill Fall 2022\\

\textit{Teaching Assistant} & ECON 4320 Public Sector Economics, University of Texas at Dallas & \hfill Spring 2022\\

\textit{Teaching Assistant} & ECON 4302 Urban and Regional Economics, University of Texas at Dallas & \hfill Fall 2021\\

\end{longtable*}

## 
